language: python

#python version
python:
  - "2.7"

before_script: -pyhton mysite/manage.py migrate
#command to install dependencies
install: pip install -r requirements.txt

#comannd to run tests
script: python mysite/manage.py test socialnet
